baseURL: 'https://celiachu.github.io'
title: 'CeliachuLife'
theme: hugo-PaperMod
license: 'MIT'
description: 'A fast, clean Hugo theme'
homepage: 'https://celiachu.github.io'
googleAnalytics: 'G-4WXJ5TEK2S'
defaultContentLanguage: 'zh'
hasCJKLanguage: true
copyright: 'All rights reserved.'

# 将分页相关设置统一写到顶层
# 如果只想用你原来写法(pagination.pagerSize)，也可保留。这里写成 Hugo 常用的 paginate: 10
paginate: 10

# 以下这几个一般是官方推荐/示例的默认值，可以照需要保留或修改
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
buildDrafts: false
buildFuture: false
buildExpired: false

# 一些官方给出的内容压缩/去除多余 XML 文件的选项
minify:
  disableXML: true

# 你原本在 Config.Services.RSS 下的配置依然保留
Config:
  Services:
    RSS:
      Limit: 10

menu:
  main:
    - name: Blog
      url: /blog
      weight: 1
    - name: Weekly
      url: /weekly
      weight: 2
    - name: Art
      url: /art
      weight: 3
    - name: Tags
      url: /tags
      weight: 4
    - name: Archive
      url: /archives
      weight: 5
    - name: Guest
      url: /guestbook
      weight: 6
    - name: Search
      url: /search
      weight: 7

params:
  # 来自官方示例的一个小标志
  env: production

  # 你原先的主要参数
  mainSections: 'weekly'
  headTitle: 'CeliachuLife'
  brand: 'HOME'
  avatarURL: '/images/avatar.png'
  author: 'Celiachu'
  email: 'celiachu2077@foxmail.com'
  authorDescription: 'Grow together through the exploration of science, the experimentation with coding, and the joy of gaming.'
  info: "Learning is not just accumulation, but a process of thinking, understanding, and growing.\n        [*RSS*](https://celiachu.github.io/index.xml)"
  favicon: 'favicon.ico'
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
    showMetaTags: true
  darkModeTheme: 'data-dark-mode'

  # ---- 以下为你已经存在的部分 ----
  comments:
    giscus:
      enable: true
      repo: 'celiachu/celiachu.github.io'
      repo_id: 'R_kgDOK2zS2A'
      category: 'Announcements'
      category_id: 'DIC_kwDOK2zS2M4Cbuo5'
      mapping: 'pathname'
      position: 'top'
      lang: 'zh-CN'

  sponsors:
    title: 'Sponsors'
    description: 'Support me by becoming a sponsor'
    buymeaCoffee:
      enable: true
      url: 'https://www.buymeacoffee.com/celiachu'
      buttom_api: 'https://img.buymeacoffee.com/button-api/?text=Buy me a coffee&emoji=&slug=iguangzhengli&button_colour=FFDD00&font_colour=000000&font_family=Cookie&outline_colour=000000&coffee_colour=ffffff'
      qr: 'https://storage.guangzhengli.com/images/buymeacoffee_sponsors.png'
    wechat:
      enable: false
    alipay:
      enable: false
  analytics:
    google:
      SiteVerificationTag: 'xxx'
    umami:
      enable: true
      website_id: '3f2ade23-d97c-46a8-95db-80ddf979cf49'
      url: 'https://umami-celiachus-projects.vercel.app/hugo-ladder'

  guestbook:
    title: 'Guestbook'
    description: 'Leave a comment below. It could be anything –- question, appreciation, information, or even humor.'
  social:
    - name: GitHub
      pre: >-
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/celiachu/celiachu.github.io'

  # ---- 以下为 PaperMod 官方常见功能(有些你已用到，或可选启用) ----
  # 显示阅读时长、面包屑导航、分享按钮、分页页码、代码行复制等
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShowPageNums: true
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: true
  ShowRssButtonInSectionTermList: true
  displayFullLangName: true
  ShowToc: true        # 是否在文章内页显示 ToC（目录）

  # 默认主题自动切换: light / dark / auto
  defaultTheme: 'auto'

languages:
  en:
    languageName: EN
  zh:
    languageName: 中
    author: Celiachu
    copyright: 版权所有。保留一切权利。
    authorDescription: 在科学的探索、编程的尝试和游戏的乐趣中共同成长
    email: "celiachu2077@foxmail.com"
    info: 学习不只是积累，而是思考、理解与成长的过程。
      [RSS订阅](https://celiachu.github.io/index.xml)
    guestbook:
      title: 留言板
      description: 您的评论，会让该网站更精彩！
    menu:
      main:
        - name: 文章
          url: /blog
          weight: 1
        - name: 周刊
          url: /weekly
          weight: 2
        - name: 生活
          url: /art
          weight: 3
        - name: 标签
          url: /tags
          weight: 4
        - name: 历史
          url: /archives
          weight: 5
        - name: 留言板
          url: /guestbook
          weight: 6
taxonomies:
  series: series
  tag: tags

