baseURL: "https://celiachu.github.io"
title: LybertiLife
copyright: "© 2025 Lyberti"
pagination:
  pagerSize: 5
theme: hugo-PaperMod
defaultContentLanguage: 'zh'
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
hasCJKLanguage: true

author:
  name: Lyberti

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "LybertiLife"
  description: "If you don't write, you're just pretending to think. ✍️"
  keywords: [Blog, Software, Life, Engineering, Art]
  author: Lyberti
  DateFormat: "2006-01-02"
  math: true
  defaultTheme: auto
  disableThemeToggle: false

  ShowFullTextInRSS: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  comments: true
  showtoc: true
  tocopen: false
  
  ShowFeaturedInHome: true
  ShowFeaturedInArchive: true

  assets:
    disableHLJS: true
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
    enabled: false
    title: LybertiLife
    imageUrl: "static/images/avatar.png"
    imageTitle: "Lyberti"
    buttons:
      - name: Weekly
        url: /weekly
      - name: Archive
        url: /archives

  homeInfoParams:
    Title: "LybertiLife"
    Content: |
      If you don't write, you're just pretending to think. ✍️
      
      话一出口，就成谬误，思想一写成文章，就显得浅薄。
      
      _-- **Lyberti**_

  socialIcons:
    - name: github
      url: "https://github.com/celiachu"
    - name: email
      url: "mailto:celiachu2077@foxmail.com"
    - name: rss
      url: "/index.xml"

  analytics:
    google:
      SiteVerificationTag: 'xxx'
    umami:
      enable: true
      website_id: '3f2ade23-d97c-46a8-95db-80ddf979cf49'
      url: 'https://umami-celiachus-projects.vercel.app/hugo-ladder'

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  editPost:
    URL: "https://github.com/celiachu/celiachu.github.io/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  giscus:
    repo: "celiachu/celiachu.github.io"
    repoId: "R_kgDOK2zS2A"
    category: "Announcements"
    categoryId: "DIC_kwDOK2zS2M4Cbuo5"
    mapping: 'pathname'
    position: 'top'
    lang: 'zh-CN'

languages:
  en:
    languageName: "English"
    subtitle: "Yet Another Programming Blog"
    weight: 2
    contentDir: 'content/en'
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Weekly
          url: /series/weekly-report/
          weight: 10
        - name: Archive
          url: /archives
          weight: 20
        - name: Blog
          url: https://blog.lyberti.xyz/
          weight: 30
        - name: Running
          url: https://running.lyberti.xyz/
          weight: 35
        - name: Podcast
          url: /podcast
          weight: 40
        - name: Tag
          url: /tags
          weight: 50
        - name: Search
          url: /search
          weight: 60
        - identifier: categories
          name: "categories"
          url: /categories/
          post: ' ▾'
          weight: 100
  zh:
    title: "LybertiLife"
    languageName: "中文"
    subtitle: "博客残本"
    contentDir: 'content/zh'
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: 周报
          url: /series/weekly-report/
          weight: 10
        - name: 归档
          url: /archives
          weight: 20
        - name: 博客
          url: https://blog.lyberti.xyz/
          weight: 30
        - name: 跑步
          url: https://running.lyberti.xyz/
          weight: 35
        - name: 播客
          url: /podcast
          weight: 40
        - name: 标签
          url: /tags
          weight: 50
        - name: 搜索
          url: /search
          weight: 50
        - identifier: series
          name: 系列
          url: /series/
          weight: 60
        - identifier: categories
          name: "分类"
          url: /categories/
          post: ' ▾'
          weight: 100

markup:
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

services:
  instagram:
    disableInlineCSS: false
  x:
    disableInlineCSS: false